spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: 12345678
    hikari:
      maximum-pool-size: 10
server:
  port: 9999